namespace DiscordBot.Rollers.EffectRollers;

public abstract class DevilsLuckRoller : IEffectRoller
{
    private static readonly Dictionary<int, string> Mutations = new()
{
    [1] = "Blackened Hands\n\"Your hands are permanently blackened and stiffened.\"\n\nYou have a -2 penalty on all Strength rolls involving your grip, but a +2 bonus on Strength rolls to punch or break objects, due to the hands being hardened and unfeeling.\n\nRoleplay Cue: You prefer to wear gloves to hide your hands. And you are terrified of shaking someone's hand, as the touch of your skin feels like old parchment.",
    [2] = "Cloven Hooves\n\"Your feet fuse, becoming cloven hooves.\"\n\nYou are now faster, with a +2 bonus on all Agility rolls related to running, but you have a -2 penalty on all Agility rolls related to balance.\n\nRoleplay Cue: You constantly have a strange, animalistic rhythm to your walk, and you are unable to stand still without shuffling.",
    [3] = "Bone Nose\n\"Your nose hardens into a brittle, bone-like spike.\"\n\nYou have a +2 bonus on all Strength rolls to headbutt or break thin objects with your nose spike (1d6).\n\nRoleplay Cue: You have a constant, low-level throb in your nose, and you are terrified of getting hit in the face in case your nose breaks and falls off.",
    [4] = "Forked Tongue\n\"Your tongue forks at the tip, like that of a serpent.\"\n\nYou can no longer speak clearly, and your words are a slurred, hissing mess. You can use your tongue to deliver a quick surprise lash. Once per day, as an action, you can make a Presence roll DR12 against a target within close range. On success, the target suffers 1d2 damage and is Stunned until their next turn from the shock and revulsion.\n\nRoleplay Cue: You are paranoid about people hearing you speak, so you resort to hand signals and whispers.",
    [5] = "Sleepwalker\n\"You are drawn to tainted artifacts and evil places while sleepwalking.\"\n\nYou cannot control your actions and will often wake up in a place you do not know, with no memory of how you got there. Once per day, you may take a Presence roll DR14. On success, you gain the precise direction and approximate distance to the nearest truly tainted artifact or evil place from your current location.\n\nRoleplay Cue: You are terrified of the dark, as you know you have no control over yourself when you are sleeping. You will do anything to avoid falling asleep.",
    [6] = "Degenerating Sight\n\"Your sight is degenerating. You are slowly going blind.\"\n\nYou suffer a -2 penalty on Agility rolls to dodge ranged attacks due to your lack of peripheral vision. People often surprise you as you don't see them coming. You also have a hard time finding people and things you are looking for, as if looking through a narrow straw.\n\nRoleplay Cue: You are terrified of the dark, and you are constantly asking your companions for help, as you can no longer trust your own eyes.",
    [7] = "Dark Rune\n\"A birthmark appears that may look like a dark rune or an evil symbol.\"\n\nYou have a -2 penalty on all Presence rolls when interacting with holy men or good-aligned people, but a +2 bonus on all Presence rolls when interacting with those of a similar dark disposition.\n\nRoleplay Cue: The rune burns and itches when you are near a holy place, and it gets hot when you are near something evil.",
    [8] = "Thirst for Warm Blood\n\"Food does not suffice, you need blood. Fresh blood, warm blood. Animal, friend or foe does not matter. As long as you can feel the heartbeat when you drink.\"\n\nYou are perpetually drained and cannot recover health until you drink warm blood from a living creature.\n\nRoleplay Cue: You have a deep, gnawing hunger for blood, and you are constantly searching for a way to sate it. You are terrified of your own hunger, as it makes you a monster.",
    [9] = "Blight Fungus\n\"A dark, sickly fungus covers your body.\"\n\nIt is a painful, itchy mess that physically drains you, giving you a -2 penalty on all Strength rolls. However, you are immune to all floral poisons, and you can find and identify poisonous mushrooms with a +2 bonus to your roll.\n\nRoleplay Cue: You are fascinated with decay and rot, as the blight has taught you the language of decomposition. You often find yourself muttering about the life cycles of fungus and rot.",
    [10] = "Bulging Veins\n\"Your veins bulge black when you experience anger or other strong emotions.\"\n\nYou feel a burning, sickly sensation, giving you a -2 penalty on all Toughness saves. However, you can see and feel blood flow in others. Once per day, as an action, you may make an eye-opening gesture. For the rest of the round, you can see all living creatures within near distance, even through solid barriers by tracing their heat and blood flow.\n\nRoleplay Cue: You have an obsessive need to be in a quiet place to listen to the sound of your own blood pumping through your veins.",
    [11] = "Evil Tongues\n\"You speak in an unknown, evil-sounding language while sleeping.\"\n\nOnce per day, as an action, you may force an incantation in this primal language while pointing at a foe. Target one enemy within range. That enemy must pass a Presence roll DR12 or suffer a -2 penalty on all rolls on their next turn due to supernatural confusion.\n\nRoleplay Cue: You are terrified of sleeping, as you have no control over the words that come out of your mouth. You fear what you might say, and you often go without sleep for days at a time.",
    [12] = "Rotting Flesh\n\"The flesh on your body begins to rot.\"\n\nYou have a -2 penalty on all Toughness saves against disease, as your rotting body is more susceptible to infection. But you have a +2 bonus on Presence rolls against undead or creatures of decay, who find your stench appealing.\n\nRoleplay Cue: You have a constant, nagging desire to be in a cold, damp place, as the cold helps slow the rot.",
    [13] = "Hoarse Voice\n\"Your voice becomes hoarse and raspy.\"\n\n-2 penalty on all Strength rolls requiring prolonged exertion or shouting.\n\nRoleplay Cue: You whisper when you can, to hide the rasp in your voice, and you are terrified of shouting.",
    [14] = "Sulfur Breath\n\"Your breath stinks of sulfur.\"\n\nYou have a -2 penalty on all Presence rolls. Once per battle, the noxious fumes concentrated in your lungs can be expelled in a corrosive cloud. As an action, target one creature within close range, they must pass a Toughness roll DR14 or take 1d4 damage and suffer a -1d2 penalty to their armor until the end of the round.\n\nRoleplay Cue: You instinctively hold your breath when you are near others, and you have a nervous tick where you constantly lick your lips.",
    [15] = "Obsidian Sweat\n\"A foul, black, tar-like substance constantly weeps from your pores. When exposed to air, this ooze hardens quickly into small, sharp, obsidian-like flakes.\"\n\nRoleplay Cue: You have a deep, personal fixation on these sharp flakes, collecting them obsessively as you believe they hold clues to your cursed future. You are highly aggressive if anyone tries to touch your \"prophecies.\"",
    [16] = "Glass Skin\n\"Your skin hardens into a glassy, brittle mess that breaks and shatters with a satisfying crunch.\"\n\nThe shards constantly fall off, leaving a trail behind you and making it impossible to move stealthily, giving you a -2 penalty on all Agility rolls to move quietly. However, you have a +2 bonus to your Toughness against piercing damage.\n\nRoleplay Cue: You are constantly aware of the sounds you are making, and you are afraid to make any sudden movements, as the sound of breaking glass is like a personal alarm.",
    [17] = "Maggot Infestation\n\"Your body is infested with maggots, and you can feel them squirming and writhing under your skin.\"\n\nRoleplay Cue: You are constantly itching and scratching your skin, and you feel a deep, personal revulsion at the thought of bugs.",
    [18] = "Hair Loss\n\"Your hair falls out, leaving you with a bald head. Your scalp is now tender and easily bruised.\"\n\nRoleplay Cue: You are obsessed with hats and wigs, and you will not leave your shelter without covering your head.",
    [19] = "The Shivering\n\"Your body is now in a constant, uncontrollable shiver.\"\n\nYou have a -2 penalty on all Agility checks, but a +2 bonus on all Toughness saves against cold damage.\n\nRoleplay Cue: You find yourself clenching your jaw to stop your teeth from chattering, and you are always seeking out warmth.",
    [20] = "Taste for Cadavers\n\"Fresh food no longer edible. Only the taste of rotting flesh will sate your hunger.\"\n\nYou must feed on something rancid every day, or you will suffer a -2 penalty on all Presence rolls until you do.\n\nRoleplay Cue: The taste of normal food is repulsive to you, and you are a constant source of disgust to your companions, as you find yourself eating rotten food.",
    [21] = "Sunlight Aversion\n\"The sun burns your unholy carcass. A true testament of your curse.\"\n\nDirect sunlight on exposed skin burns you for 1d4 damage per minute. You must now hide from the sun or risk a slow, agonizing death.\n\nRoleplay Cue: You feel a deep, personal connection to the night, and you are terrified of the sun. You will not leave your shelter during the day.",
    [22] = "Skeletal Form\n\"Your body withers away, leaving you gaunt and sickly.\"\n\nYou have a -2 penalty on all Strength rolls to carry or lift, but a +2 bonus on all Agility rolls to squeeze through small spaces or hide in shadows.\n\nRoleplay Cue: You have an obsessive need to eat as much as possible, as you feel your body withering away, but nothing you eat can make you gain weight.",
    [23] = "Bleeding Orifice\n\"A bleeding orifice appears on your body. The wound will never heal, and it will constantly bleed and ooze a foul, black liquid.\"\n\nYou have a -2 penalty on all Strength rolls to run or pursue, due to constant, low-level blood loss. But you also have a +2 bonus on all Toughness saves to resist blood-based attacks.\n\nRoleplay Cue: You are obsessed with the sight of your own blood, and you find a strange comfort in the constant bleeding.",
    [24] = "Festering Wound\n\"A festering wound appears on your body and will not heal. It constantly oozes pus, and the stench of decay follows you everywhere you go.\"\n\nRoleplay Cue: You are always trying to hide the wound, as you are ashamed of the disgusting sight and smell.",
    [25] = "Eyes that Weep Blood\n\"Your eyes constantly weep tears of blood. The tears are a constant, painful presence that makes it difficult to see.\"\n\nRoleplay Cue: You are obsessed with the sight of your own blood, and you find a strange comfort in the constant bleeding.",
    [26] = "Scaly Skin\n\"Your skin becomes scaly and rigid, devoid of feeling.\"\n\nYou have a natural armor of 1d2, adding to other armor. But suffer a -2 penalty on Agility rolls requiring fine tactile movement as your body is stiff.\n\nRoleplay Cue: You have a constant, deep itch under your scales that you can never truly scratch, causing you to constantly shift and rub against rough surfaces.",
    [27] = "The Dream Eater\n\"While you sleep, you compulsively eat strange, inedible things, such as dirt, cloth, or raw components. You always wake up with a mouth full of grit and a strange, non-mechanical insight into the consumed substance.\"\n\nRoleplay Cue: You have a severe aversion to sleeping near anything valuable or delicate, and you constantly check your inventory upon waking for anything that might have been \"sampled.\"",
    [28] = "Corpse's Body\n\"Your body is as cold as a corpse or feverishly hot.\"\n\nYou have a -2 penalty on all Toughness saves against cold or heat, but a +2 bonus on all rolls against damage from the other.\n\nRoleplay Cue: You are always feeling like you are in the wrong place, either too cold or too hot, and you are constantly shifting and squirming in your skin.",
    [29] = "Inverted Eyes\n\"The color of your eyes inverts, the whites becoming black and the irises a sickly yellow.\"\n\nYour vision is now impaired in bright light.\n\nRoleplay Cue: You have a strong aversion to direct sunlight, and you constantly squint and turn your head away from the sun.",
    [30] = "Odor of Decay\n\"A faint odor of decay follows you.\"\n\nYou have a -2 penalty on all Presence rolls to interact with others, but a +2 bonus on your Presence rolls to scare or intimidate an enemy.\n\nRoleplay Cue: You have a deep, personal aversion to sweet smells and flowers, as they make you feel sick to your stomach.",
    [31] = "The Hunger\n\"You have a constant, insatiable hunger that will never be sated. You must constantly eat, or you will suffer from a gnawing pain in your gut that makes it impossible to think...\"\n\nRoleplay Cue: You are constantly snacking on anything you can get your hands on, as you are afraid of the return of hunger.",
    [32] = "Fangs and Claws\n\"Your fangs and nails elongate into sharp claws and talons. They are brittle and weak, and they will snap and break with the slightest impact.\"\n\nYour claws and fangs can be used as a natural weapon that deals 1d4 damage. However, because they are brittle, if you roll a 1 on the damage die, the tooth or claw shatters and you suffer 1 point of damage from the painful impact.\n\nRoleplay Cue: You have a deep-seated fear of using your claws, as you know they will break and cause you immense pain.",
    [33] = "Discolored Skin\n\"Your skin is mottled with severe rashes and blemishes.\"\n\nYou have a -2 penalty on all Presence rolls, as people are repulsed by your appearance. However, you have a +2 bonus to your Toughness against disease.\n\nRoleplay Cue: You are always hiding your skin, and you feel a deep shame and fear of being seen.",
    [34] = "Taste for Raw Meat\n\"Nothing can satisfy your hunger as much as the taste of raw meat straight from the bone.\"\n\nYou must feed on fresh, raw meat every day, or you will suffer a -2 penalty on all Presence rolls and a -2 penalty to your Strength rolls until you feed.\n\nRoleplay Cue: You have a deep, animalistic craving for raw meat, and you are constantly searching for it. You are terrified of your own hunger, as it makes you a beast.",
    [35] = "Vicious Teeth\n\"Your teeth elongate, becoming sharp and vicious like those of a beast.\"\n\nYou must make a Presence roll DR12 to avoid biting someone when angered. On failure, you immediately bite the nearest creature for 1d4 damage.\n\nRoleplay Cue: You are paranoid about speaking, as you fear your sharp teeth might slip and bite someone. You have a constant, deep-seated fear of your own mouth.",
    [36] = "Brittle Bones\n\"Your bones become as brittle as glass, and any sudden impact can cause them to shatter.\"\n\nYou have a -2 penalty on all Toughness saves against bludgeoning damage. However, you are immune to becoming Deafened, as your brittle bones transmit all sound vibration directly and painfully into your inner ear.\n\nRoleplay Cue: You constantly feel like you are made of glass, and you are terrified of any sudden movements or impacts.",
    [37] = "Withered Limbs\n\"One of your limbs withers away, becoming a useless, brittle stick.\"\n\nYou have a -2 penalty on all Agility rolls involving that limb, but a +2 bonus to your Presence when intimidating a foe with your grotesque appearance.\n\nRoleplay Cue: You constantly twitch the withered limb, as you feel phantom pains and an electric current of energy constantly running through it.",
    [38] = "Bony Horns\n\"Small bony horns sprout from your thick forehead.\"\n\nYou can attempt a headbutt attack as an action. Make a Strength roll DR12 against a target within close range. On success, you suffer 1d2 damage, but the target must immediately move 1 square away from you, with no chance of retaliation.\n\nRoleplay Cue: You must rub your horns against hard surfaces to relieve a constant, maddening itch.",
    [39] = "Noxious Fumes\n\"You constantly emit a noxious gas from your pores.\"\n\nThe gas is a sickening, green mess that makes people sick, giving you a -2 penalty on all Presence rolls. However, you are immune to all gases and poisonous fumes.\n\nRoleplay Cue: You have a hard time breathing in clean air, and you constantly feel a need to be in a place with poor air quality.",
    [40] = "Eyes of Coals\n\"Your eyes glow in the dark, like hot coals.\"\n\nYou can no longer hide in the dark, as your eyes are like torches in the dark. However, you gain perfect vision in all degrees of darkness. Furthermore, your eyes can ignite flammable material within near range if you stare at it for 2 turns and pass a Toughness roll DR12.\n\nRoleplay Cue: You cannot help but look at others for too long, as your eyes feel like they are constantly burning.",
    [41] = "Vile Ooze\n\"You constantly ooze a vile, black goo from your pores.\"\n\nThe goo is a sickening, foul-smelling mess, giving you a -2 penalty on all Presence rolls. However, you are immune to all acids and poisons.\n\nRoleplay Cue: You constantly feel the urge to clean yourself, but the goo is always there, no matter how hard you scrub.",
    [42] = "The Tail\n\"You grow a tail. It is a useless appendage that constantly gets in the way.\"\n\nYou have a -2 penalty on all Agility rolls to move quickly, but a +2 bonus to your Agility to balance on narrow or slippery surfaces.\n\nRoleplay Cue: Your tail has a mind of its own and will often twitch and move when you are scared or angry.",
    [43] = "Dark Streaks\n\"Dark streaks appear in your blood, visible when you bleed.\"\n\nThe streaks are a physical manifestation of your corruption. You have a -2 penalty on all Toughness saves against poison, but you have a +2 bonus on all Toughness saves against disease.\n\nRoleplay Cue: When you are cut, you find yourself staring at your black blood with a morbid fascination, as it reminds you of your pact.",
    [44] = "Bursting Boils\n\"Boils appear in your mouth, throat, and ears, and they burst at inopportune times.\"\n\nYou are now deafened, and every time a boil bursts, you take 1d4 damage.\n\nRoleplay Cue: You have a constant, high-pitched ringing in your ears, and you are always rubbing at your ears as if to stop the ringing.",
    [45] = "Black Mucus\n\"Your mucus is now black and thick, and it drips from your nose and mouth at all times.\"\n\nRoleplay Cue: You are obsessed with cleanliness, and you constantly wipe your nose and mouth with a rag, as you are afraid of the black mucus staining your clothes.",
    [46] = "Twisted Form\n\"Your body is now a twisted, grotesque mockery of your former self as limbs grow and diminish to abnormal proportions.\"\n\nYou are in constant, agonizing pain and cannot wear any armor. Your grotesque, hardened form gives you a natural armor -1d4. This benefit does not stack with any other armor.\n\nRoleplay Cue: You have a hard time sleeping at night, as your body is in constant pain, causing you to writhe and thrash in your sleep. People rarely take you for human given the shape of your body.",
    [47] = "Spinal Spikes\n\"Your spine grows spikes that erupt from your back, splitting the skin.\"\n\nYou cannot wear armor unless it has been customized for you, tripling its cost. When you are successfully struck by a melee attack, you can immediately spend an action to retaliate. The attacker must pass an Agility roll DR12 or take 1d4 damage as they are shredded by the spikes.\n\nRoleplay Cue: Every time you move, you feel a sharp, stabbing pain, causing you to groan with effort and making you unable to stand still.",
    [48] = "Twitching Muscles\n\"Your muscles constantly twitch and spasm.\"\n\nYou have a -2 penalty on all Agility rolls to move quietly, but a +2 bonus to your Strength when making a quick, powerful strike.\n\nRoleplay Cue: You are a jittery mess, and you have a hard time standing still, as your muscles constantly want to move.",
};

    public static string Roll()
    {
        var d6 = Random.Shared.Next(1,7);
        var dice = Random.Shared.Next(1, Mutations.Count + 1);

        return d6 == 1
            ? $"```🎲 DEVIL'S LUCK ROLL 🎲\nD6: {d6} | Result: {dice}\n\n⚖️ A DEVIL'S BARGAIN ⚖️\nThe figure with the ledger marks something in their book with a knowing smile...\n\n🔥 THE COST OF YOUR SECOND CHANCE MANIFESTS:\n\n{Mutations[dice]}\n\nThe transformation begins... there is no going back.```"
            : $"```🎲 DEVIL'S LUCK ROLL 🎲\nD6: {d6}\n\n📜 The figure with the staff nods approvingly.\nYour debt remains... unpaid. For now.```";
    }
}