namespace DiscordBot.Rollers.EffectRollers;

public abstract class WoundRoller : IEffectRoller
{
    private static readonly Dictionary<int, string> Wounds = new()
    {
        [1] = "Lost Eye\n“A jagged shard of metal or the splinter has carved a bloody, gaping hole where your eye once was. It is a wet, bloody mess. You can only see half of the world, a permanent and terrifying form of tunnel vision that leaves you vulnerable to a foe you cannot see.”\n\nConsequences: Your perception is permanently diminished. Depth perception is gone, and ranged attacks are now a desperate gamble. The lost eye is a permanent scar, a visible sign that will either mark you as a monster or as a veteran of a thousand wars.",
        [2] = "Jaw Fracture\n“Your jaw is turned into a useless, agonizing mess of shattered bone and torn gristle. Your mouth hangs at an unnatural angle, and every attempt to speak or eat is met with a stabbing pain.”\n\nConsequences: Communication is now an act of pure will. Your speech is a pained, slurred mess of groans and grunts that makes it almost hard to be understood by anyone not intimately familiar with you. Eating requires soft food to be viable and without agonizing pain.",
        [3] = "Lost Teeth\n“Your mouth is a bloody, painful ruin. Some of your teeth are gone forever, leaving gaps where they once were, and the remaining ones are loose and fragile. Your grin is now gruesome and your speech is punctuated with a lisping whistling hiss where your teeth once were.”\n\nConsequences: You cannot talk without a sibilant hiss or a lisp, and your words may become a source of ridicule from others. The act of eating is a chore and you must now subsist on soft food.",
        [4] = "Concussion\n“Your head is left with a throbbing, pounding headache. Your thoughts are hazy and difficult to follow and the world seems to spin around you. Every sudden noise or movement sends a painful, shocking jolt through your skull and you find it difficult to remember what you were doing.”\n\nConsequences: You find it difficult to recall important details, solve complex problems, or even hold a thought in your head. You may stutter or stare blankly at your companions when asked a question, as your mind struggles to grasp even the simplest of ideas.",
        [5] = "Injured Hearing\n“You are left with a high-pitched ringing in your ears that will not go away. It is an incessant, maddening whine that makes it difficult to hear anything else as it is a constant debilitating presence in your life.”\n\nConsequences: This wound introduces a maddening constant noise. You are unable to hear quiet sounds, whispers, or any subtle movement around you. You must now rely on your other senses and your companions to navigate the world. A sudden loud noise will cause you to wince in pain and lose focus.",
        [6] = "Fractured Skull\n“The skull is cracked, a brittle cage that now struggles to hold your mind. You are a hair's breadth from a deeper, more permanent injury. The world is a blurry, hazy mess, and every step is a risk, a gamble that you might not be able to stand on your own.”\n\nConsequences: You are prone to a sudden loss of consciousness. The slightest impact or even a strong, sudden movement can cause you to fall into a stupor, leaving you vulnerable to attack or to the whims of your enemies. The constant, agonizing pain will also make it difficult to focus on anything else, and you may find yourself struggling to stay awake.",
        [7] = "Punctured Lung\n“Something has plunged deep into your chest. There is little blood, but a sickening, wet whistling with every gasp you take. Each breath is a struggle, and you can feel the air escaping from your lungs. The wound is a quiet, terrifying threat, every breath you take, you may be closer to a suffocating, agonizing end.”\n\nConsequences: Any strenuous activity, such as running, fighting, or even a desperate retreat, will leave you gasping for air. You will find yourself quickly exhausted, your body unable to keep up with the demands of the world. This wound makes prolonged physical activity a fatal gamble, as you can only push yourself so far before you simply run out of breath and collapse.",
        [8] = "Fractured Ribs\n“The sickening crunch of your ribs sends a shockwave of pain through your chest. Your ribs are cracked, a brittle cage that now presses against your lungs with every breath you take. It is a constant, stabbing pain that makes it difficult to breathe and the fear of a broken rib piercing your lung is a terrifying, constant presence.”\n\nConsequences: Movement is now a painful ordeal. Walking or running sends a deep, agonizing stab of pain through your chest and every breath is shallow and difficult. You will find yourself unable to take quick, decisive actions, as you must constantly worry about the possibility of a sudden, crippling pain.",
        [9] = "Gut Wound\n“You are left with a bloody, gaping wound in your abdomen. The gash is a raw, screaming mess of bleeding flesh, and you can feel your intestines shifting underneath your hands. The wound is a leaking hole that makes you feel as though your life is constantly draining away as your intestines try to leave your body.”\n\nConsequences: This wound is a death sentence without immediate medical attention. The character is in a race against time to find a way to stop the bleeding and patch the hole in their gut. You will need to get it stitched and bandaged immediately. Even with a successful treatment, this is a terrible, life-threatening injury that will require constant vigilance to avoid a fatal infection.",
        [10] = "Ruptured Organs\n“You are left with an internal bleeding, a silent killer that no one can see. You are pale, clammy and a deep, thrumming pain radiates from your insides. You can feel your own organs screaming in protest. A deep, sickening dread fills you as you know that something is wrong and you do not have the power to stop it.”\n\nConsequences: This wound is a race against time, a desperate choice between two terrible fates: bleeding out and dying from infection or getting gruesome surgery in time. The internal trauma will kill you without immediate, invasive surgery. If you find someone brave enough to cut you open, you will be left with a terrible scar and a body that will never be the same again.",
        [11] = "Blasted Groin\n“Your groin is a raw, bloody ruin. The wound is a shocking, gruesome sight, and the pain is a high-pitched, screaming agony that leaves you unable to even think.”\n\nConsequences: The simplest of actions, such as walking or even standing, are a screaming, agonizing ordeal. This wound is a personal horror, a private agony that will leave you unable to do anything that you used to with your favorite appendage. This will forever mark you as a survivor of the worst kind of trauma, a broken person with a broken future, and feature…",
        [12] = "Festering Back Wound\n“A jagged wound on your back has become a foul, festering pit of decay. The flesh will turn mottled green and black, swollen with pus, and the stench of rot will cling to you like a shroud. A constant, burning ache radiates from the infection and you can feel the poison spreading through your body, a silent, creeping corruption.”\n\nConsequences: The infection consumes you, slowly rotting you from the inside out. The wound will constantly ooze pus, making rest a constant, disgusting affair. The stench and sight of the wound will make you a pariah, and you will be forced to hide your wound from others. This wound must be treated methodically and often.",
        [13] = "Lost Limb (Arm/Hand)\n“The attack has severed your hand or arm. The stump is a mangled, bloody ruin of bone and gristle, a raw and screaming testament to your failure. The pain is not a single, sharp agony, but a phantom ache, a ghost limb that forever reminds you of what you've lost.”\n\nConsequences: Your arm is gone forever. All actions that require two hands are now impossible. To survive, you must find a way to patch the stump before the flesh rots or you bleed out. If you are successful, you may have the opportunity to replace the missing limb with a crude wooden hook or a shard of rusted metal, a grim new extension of your body.",
        [14] = "Dislocated Shoulder\n“Your shoulder is torn from its socket. The joint is a swollen, deformed mass of flesh, and every twitch of your muscles sends a sickening shockwave of pain down your arm. You find it difficult to even lift the arm, let alone use it with any purpose.”\n\nConsequences: Using this arm to perform a strenuous action, such as swinging a sword or hefting a heavy object, risks further trauma. A forceful movement will cause the limb to fail you completely, forcing you to drop whatever you're holding with a cry of pain. Even though forced back to its socket, it is weak and can now fail again by strenuous activity over the coming weeks.",
        [15] = "Broken Fingers\n“The sharp, sickening crunch of bone as your hand is crushed. Your fingers are twisted, bent at unnatural angles, swollen and bruised with internal bleeding. Each finger is a separate, throbbing wound, a claw of agony where once was a hand of purpose.”\n\nConsequences: Your grip is now a treacherous thing. Any task requiring fine manipulation, such as picking a lock, reloading a complex firearm, or drawing a detailed map, is an agonizing and clumsy ordeal. You must find new ways to interact with the world, adapting to your newly crippled hand until it has healed.",
        [16] = "Pulled Wrist\n“The tendons of your wrist are stretched beyond their limit. A deep, throbbing ache now radiates from the joint, making it feel weak and unreliable. The sensation is like a wet rag being wrung out, a constant discomfort that makes every action a conscious effort.”\n\nConsequences: You are completely unable to hold anything in this hand that requires a firm, stable grip. The wrist simply can't bear the strain, and anything you try to hold will slip from your grasp. You'll need to rely on your other hand or find creative ways to accomplish tasks you once took for granted.",
        [17] = "Festering Wound\n“What started as a simple cut has become a weeping, swollen mess. The flesh around the wound is now a sickly shade of green and purple, hot to the touch, and stinks of rot. A thick, yellowish pus oozes from the gash.”\n\nConsequences: This wound is a ticking clock of decay. You must tend to it constantly, cleaning the pus and foulness from the open sore. Fail to do so, and the infection will spread, leading to a lingering, miserable sickness that can only be cured with the most gruesome and painful of medical treatments. The stench and sight of the wound will also make social encounters difficult, as most people would rather not be near the walking dead.",
        [18] = "Gaping Wound\n“A deep, jagged gash on your arm that won't stop bleeding. The cut is so deep you can see the white of the bone underneath, and the blood pumps from it in a slow, steady rhythm. The wound itself is an open mouth, constantly consuming your life force.”\n\nConsequences: This wound is a liability, a constant drain on your vitality. The bleeding will not stop on its own, and you will grow weaker over time. You must find a way to staunch the flow of blood, or you will find yourself dizzy, exhausted, and incapable of any strenuous action. The blood trail you leave behind may also be a beacon for any number of lurking beasts or vicious foes.",
        [19] = "Gaping Wound\n“The leg has been split open by a jagged blade or a close-range blast. The gash runs deep, revealing slick, red muscle and white tendons beneath. The wound is an open, hungry maw that will not clot, and with every step, the blood pumps from it like a dying heartbeat, painting a gruesome trail behind you.”\n\nConsequences: This wound bleeds relentlessly. You must find a way to staunch the flow of blood, or die a slow death. In addition to the direct effects of the wound, the blood trail it leaves is a beacon for scavengers and beasts, making any rest or attempt at stealth a treacherous gamble.",
        [20] = "Festering Wound\n“A seemingly minor scrape has now blossomed into a vile, weeping horror. The skin around the wound is mottled green and black, slick with pus, and hot to the touch. The stench of decay follows you like a shadow, and a constant, deep ache radiates from the infection. It feels like a hungry thing is eating you from the inside out, consuming you one painful, miserable day at a time.”\n\nConsequences: The infection consumes your body, sapping your strength and will. The character will become slow and lethargic. You must tend to the wound constantly, cleaning the foulness, lest the rot spread further. The festering smell will make you a pariah, and you will be forced to keep a distance from others. The longer you go without proper treatment, the more the fever and lethargy will consume you.",
        [21] = "Twisted Ankle\n“Your ankle is a swollen, bruised mockery of a joint. The slightest pressure sends a shock of blinding agony up your leg. Walking is a slow methodical crawl of pain. The instability of the joint makes you feel like you are always on the verge of falling.”\n\nConsequences: Every single step is a choice and a struggle. Movement is now a painful and risky ordeal. You must take your time, and be careful with your footing, or risk a sudden, debilitating fall. Running is out of the question, and any quick movement will bring you to your knees with a cry of pain.",
        [22] = "Lost Limb (Leg/Foot)\n“Your leg is gone. Torn from you. The stump is a bloody, weeping mess of meat and bone, and the ground around you is slick with your life's blood. The weight of your body is now a crushing pressure on a limb that is no longer there, and every movement is a desperate, lurching struggle.”\n\nConsequences: Your leg is gone forever, making movement a constant, agonizing ordeal. Your speed is significantly reduced, and you will never again be able to run. You must rely on a crude crutch or the assistance of your allies to get around. If you are lucky, you might eventually find a sawbones with the skill to fit you with a crude pegleg, a noisy and cumbersome replacement that will forever mark you as a survivor of the world's endless misery.",
        [23] = "Dislocated Knee\n“Your kneecap has been knocked clean out of its socket. The joint is a grotesque, misshapen horror, and a sharp, stabbing pain shoots up your leg every time you attempt to straighten it. The limb is unstable and unpredictable.”\n\nConsequences: The knee will give out on you without warning. You are always at risk of your leg failing. This makes you constantly wary and unsure of your footing. Even if you manage to rise, a sudden lurch or a moment of carelessness will send you tumbling to the ground.",
        [24] = "Severe Muscle Tear\n“A deep, burning tear in the muscle of your leg leaves a searing pain that cripples you. The flesh is bruised and swollen, and the muscle feels as though it is ripping further with every step. Exhaustion is a constant companion, as every use of the muscle feels like a monumental effort.”\n\nConsequences: The wound makes any rapid movement a monumental effort that leaves you utterly drained. The character is unable to run or sprint, as every sudden movement causes agonizing pain and a crushing fatigue that will leave you gasping for breath. This wound makes escape, retreat, or a sudden charge a truly desperate measure.",
    };

    public static string Roll()
    {
        var dice = Random.Shared.Next(1, Wounds.Count + 1);

        return
            $"```🎲 WOUND ROLL 🎲\nResult: {dice}\n\n⚔️ THE BATTLEFIELD TAKES ITS TOLL ⚔️\nYour body bears the scars of combat...\n\n🩸 WOUND SUSTAINED:\n\n{Wounds[dice]} \n\nThe injury will serve as a reminder of this battle.```";
    }
}